name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build

      - name: Copy CSS to src folder
        run: cp ./src/style.css ./dist/src/style.css
      
      - name: Copy images to img folder
        run: cp -r ./img ./dist/img

      - name: Copy scripts to scripts folder
        run: cp -r ./scripts ./dist/scripts
      
      - name: Copy html pages to html folder
        run: cp -r ./html ./dist/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Print GitHub Pages URL
        run: echo "Your site is live at https://yupanyeinhtoon.github.io/resume/"